--- 

  - name: Create file
    connection: local
    gather_facts: false
    hosts: all

    tasks:
      - name: test
        file:
          path: /tmp/test.txt
          state: touch
          mode: '0755'
